MovieUI/Models/ErrorViewModel.cs
using System;

namespace MovieUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieUI/Models/FilmsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Models
{
    public class FilmsViewModel
    {
        public List<Movie.Domain.Entities.Film> Films { get; set; }
        public List<Movie.Domain.Entities.Salon> Salons { get; set; }
        public string BaslangicDate { get; set; }
        public string BitisDate { get; set; }
    }
}

MovieUI/Models/ReleaseFilmViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Models
{
    public class ReleaseFilmViewModel
    {
        public List<Movie.Application.Dto.FilmSalonDto> FilmSalonDtos { get; set; }
        public Movie.Domain.Entities.Salon Salon { get; set; }
    }
}

MovieUI/Models/ReleaseSalonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Models
{
    public class ReleaseSalonViewModel
    {
        public List<Movie.Application.Dto.FilmSalonDto> FilmSalonDtos { get; set; }
        public Movie.Domain.Entities.Film Film { get; set; }
    }
}

MovieUI/Controllers/FilmController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Movie.Application.Interfaces.Repository;
using Movie.Persistence.EntityFramework;
using MovieUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Controllers
{
    [Authorize]
    public class FilmController : Controller
    {
        public readonly ISalonService _salonService;
        public readonly IFilmService _filmService;

        public FilmController(IFilmService filmService, ISalonService salonService)
        {
            _filmService = filmService;
            _salonService = salonService;
        }
        public IActionResult Index(DateTime baslangic, DateTime bitis)
        {
            var model = new FilmsViewModel();

            model.Salons = _salonService.GetAll();

            if(baslangic != DateTime.MinValue && bitis != DateTime.MinValue)
            {
                model.BaslangicDate = baslangic.ToString("yyyy-MM-dd");
                model.BitisDate = bitis.ToString("yyyy-MM-dd");
                //ViewBag.baslangictarih = baslangic.ToString("yyyy-MM-dd");
                //ViewBag.bitistarih = bitis.ToString("yyyy-MM-dd");
                model.Films = _filmService.GetAll(a => a.YearOfConstruction >= baslangic && a.YearOfConstruction <= bitis);
              
            }
            else
            {
                model.Films = _filmService.GetAll();
            }
            
            return View(model);
        }

        [HttpGet]
        public IActionResult AddFilm()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AddFilm(Movie.Domain.Entities.Film film)
        {
            _filmService.Add(film);
           
           
            return RedirectToAction("Index", "Film");
        }

        [HttpPost]
        public IActionResult AddFilmRelease(int FilmId,DateTime ReleaseDate, int SalonId)
        {
            ((EfFilmService)_filmService).AddFilmToSalon(_filmService.Get(a => a.Id == FilmId), new Movie.Domain.Entities.Salon { Id = SalonId }, ReleaseDate);

            return RedirectToAction("Index", "Film");
        }

        public IActionResult DeleteFilm(int modelid)
        {
            _filmService.Delete(_filmService.Get(a => a.Id == modelid));
            
            return RedirectToAction("Index", "Film");
        }

        public IActionResult UpdateFilmPartial(int Id)
        {
            var model = _filmService.Get(a => a.Id == Id);
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult UpdateFilm(Movie.Domain.Entities.Film film)
        {
            _filmService.Update(film);

            return RedirectToAction("Index", "Film");
        }
        public IActionResult ReleaseSalons(int FilmId)
        {
            var model = new ReleaseSalonViewModel();
            model.FilmSalonDtos = ((EfFilmService)_filmService).GetSalonsByFilmId(FilmId);
            model.Film = _filmService.Get(a => a.Id == FilmId);
            return View(model);
        }
        
    }
}

MovieUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Movie.Application.Interfaces.Repository;
using MovieUI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly ISalonService _salonService;
        public HomeController(IFilmService filmService, ISalonService salonService)
        {
            _filmService = filmService;
            _salonService = salonService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Film");
        }

    }
}

MovieUI/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Movie.Application.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MovieUI.Controllers
{
    public class LoginController : Controller
    {
        public readonly IUserService _userService;
        public LoginController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string UserName,string Password)
        {
            var user = _userService.Get(a => a.UserId == UserName && a.Password == Password);
            if(user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,UserName)
                };
                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);

                return RedirectToAction("Index", "Home");
            }
            {
                return RedirectToAction("Index");
            }
           
        }


        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }
    }
}

MovieUI/Controllers/SalonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Movie.Application.Interfaces.Repository;
using Movie.Persistence.EntityFramework;
using MovieUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieUI.Controllers
{
    [Authorize]
    public class SalonController : Controller
    {

        public readonly ISalonService _salonService;
        public readonly IFilmService _filmService;

        public SalonController(IFilmService filmService, ISalonService salonService)
        {
            _filmService = filmService;
            _salonService = salonService;
        }
        public IActionResult Index()
        {
            var salons = _salonService.GetAll();
            return View(salons);
        }

        public IActionResult ReleaseFilms(int SalonId)
        {
            var model = new ReleaseFilmViewModel();
            model.FilmSalonDtos = ((EfSalonService)_salonService).GetFilmsBySalon(SalonId);
            model.Salon = _salonService.Get(a => a.Id == SalonId);
            
            return View(model);
        }


        
    }
}

MovieUI/Views/Film/AddFilm.cshtml
@{
    Layout = "_Layout";
}

<div class="container">
    <form method="post" enctype="multipart/form-data" asp-controller="Film" asp-action="AddFilm">
        <table>
            <tr>
                <td>Film Adı: </td>
                <td><input class="form-control" type="text" required id="Name" name="Name" /></td>
            </tr>
            <tr>
                <td>Yapım Tarihi: </td>
                <td><input class="form-control" type="date" required id="YearOfConstruction" name="YearOfConstruction" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input class="btn btn-primary" type="submit" value="Ekle" /></td>
            </tr>
        </table>
        <hr />
    </form>
</div>

MovieUI/Views/Film/Index.cshtml
@model FilmsViewModel;

<div class="container">
    <form action="@Url.Action("Index","Film")" method="get">
        <label>Başlangıç Tarih</label>
        <input type="date" name="baslangic" value="@Model.BaslangicDate" />
        <label>Bitiş Tarih</label>
        <input type="date" name="bitis" value="@Model.BitisDate" />
        <button type="submit" class="btn btn-primary">Listele</button>
    </form>
    <a class="btn btn-success" href="@Url.Action("Index","Film")">Aramayı Temizle</a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Film Adı</th>
                <th scope="col">Yayınlanma Tarihi</th>
                <th scope="col">Gösterime Girdiği Salonlar</th>
                <th scope="col">Gösterime Ekle</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Films.OrderByDescending(a => a.YearOfConstruction))
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Name</td>
                    <td>@item.YearOfConstruction</td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("ReleaseSalons","Film", new { FilmId =item.Id })">Gösterime Girdiği Salonlar</a>
                    </td>
                    <td>
                        <form action="/Film/AddFilmRelease" method="post">
                            <input type="hidden" name="FilmId" value="@item.Id" />
                            <input type="date" name="ReleaseDate" required />
                            <select name="SalonId">
                                @foreach (var salon in Model.Salons)
                                {
                                    <option value="@salon.Id">@salon.Name</option>
                                }
                            </select>
                            <button type="submit" class="btn btn-primary">Gösterime Ekle</button>
                        </form>
                    </td>
                    <td>
                        <a href="#" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" onclick="UpdateModal(@item.Id)">Güncelle</a>
                    </td>
                    <td>
                        <form action="@Url.Action("DeleteFilm", "Film")" method="delete">
                            <input type="hidden" name="modelid" value="@item.Id" />
                            <input class="btn btn-danger" type="submit" value="Delete" />
                        </form>
                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Güncelle</h5>
                <button type="button" class="closeModal close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
               
            </div>
            <div class="modal-footer">
                <button type="button" class="closeModal btn btn-secondary" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    
    function UpdateModal(ortakId) {
        var url = '@Url.Action("UpdateFilmPartial", "Film")';
        url += '/?Id=' + ortakId;

        $.post(url, function (data) { })
 
            .done(function (data) {

                $("#exampleModal .modal-body").html(data);
     
                $("#exampleModal").modal("show");
            })
    }
</script>

MovieUI/Views/Film/ReleaseSalons.cshtml
@model ReleaseSalonViewModel

<div class="container">
    <div class="row">
        <h2>@Model.Film.Name Filmi</h2>

        <ul class="list-group">
            @foreach (var item in Model.FilmSalonDtos)
            {
                <li class="list-group-item">@item.SalonName adlı film @item.ReleaseDate tarihinde gösterime girmiştir.</li>

            }
        </ul>

    </div>
</div>

MovieUI/Views/Film/UpdateFilmPartial.cshtml
@model Movie.Domain.Entities.Film

    <form method="post" enctype="multipart/form-data" asp-controller="Film" asp-action="UpdateFilm">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="CreatedDate" value="@Model.CreatedDate" />
        <table>
            <tr>
                <td>Film Adı: </td>
                <td><input type="text" id="Name" name="Name" value="@Model.Name" /></td>
            </tr>
            <tr>
                <td>Yapım Tarihi: </td>
                <td><input type="date" id="YearOfConstruction" value="@Model.YearOfConstruction.Value.ToString("yyyy-MM-dd")" name="YearOfConstruction" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Güncelle" class="btn btn-success" /></td>
            </tr>
        </table>
        <hr />
    </form>

MovieUI/Views/Home/Index.cshtml
@model List<Movie.Domain.Entities.Salon>
@{ ViewData["Title"] = "Home Page"; }

MovieUI/Views/Login/Index.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                 
                                    <form action="@Url.Action("Index","Login")" method="post">
                                        <div class="form-floating mb-3">
                                            <input class="form-control" name="UserName" type="text" placeholder="user name" />
                                            <label for="inputEmail">User Name</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" name="Password" type="password" placeholder="Password" />
                                            <label for="inputPassword">Password</label>
                                        </div>
   
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                         
                                            <button class="btn btn-primary" type="submit">Login</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>

MovieUI/Views/Salon/Index.cshtml
@model List<Movie.Domain.Entities.Salon>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Salon</th>
            <th scope="col">Gösterime Giren Filmler</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Name</th>
                <td><a class="btn btn-primary" href="@Url.Action("ReleaseFilms","Salon", new { SalonId=item.Id })">Gösterime Giren Filmler</a></td>
                <td></td>
                <td></td>
            </tr>
        }

    </tbody>
</table>

MovieUI/Views/Salon/ReleaseFilms.cshtml
@model ReleaseFilmViewModel

   <div class="container">
       <div class="row">
           <h2>@Model.Salon.Name Gösterime Giren Filmler</h2>

           <ul class="list-group">
               @foreach (var item in Model.FilmSalonDtos)
               {
                   <li class="list-group-item">@item.FilmName adlı film @item.ReleaseDate tarihinde gösterime girmiştir.</li>

               }
           </ul>

       </div>
   </div>

MovieUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Movie App</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Movie App</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto" style="margin-right:15px;">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("LogOut","Login")">Çıkış Yap</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">*****</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Anasayfa
                        </a>
                        <div class="sb-sidenav-menu-heading">*****</div>
                        <a class="nav-link" href="@Url.Action("Index","Salon")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Salonlar
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Filimler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index","Film")">Filmler</a>
                                <a class="nav-link" href="@Url.Action("AddFilm","Film")">Film Ekle</a>
                            </nav>
                        </div>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Movie App
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    <script>
        $(".closeModal").click(function () {
            $("#exampleModal").modal("hide");
        });
    </script>
</body>
</html>